# EnderDragonTweaks - Ender Dragon tweaks, mainly for SMP servers
# by EvsDev (https://github.com/evs-dev)
# contributors: https://github.com/evs-dev/EnderDragonTweaks/graphs/contributors
# CONFIGURATION FILE
# ❗ IMPORTANT INFO: ❗
# - Most strings support using the ampersand (&) symbol for colours and formats (https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes)
# - Macros are placeholders you can include in strings that are replaced by the plugin
# - Every string that has macros has a comment above explaining them
# - Every string requires quotes ("example string") unless the default does not have them
# - 20 ticks = 1 second
# - This plugin uses bStats. To opt out of its anonymous stats collection, find the bStats folder in your plugins folder and set enabled to false in its config
# - (https://bstats.org/plugin/bukkit/EnderDragonTweaks/12284)

# Config version - DO NOT CHANGE (is set by plugin)
version: 0

# Is the plugin enabled?
# DEFAULT: true
enabled: true

# The delay in ticks between the death of the Dragon and when this plugin triggers
# DEFAULT: 80
delay: 80

# The radius (in blocks) from the centre of the End island where players will be counted as Dragon fight participants
# DEFAULT: 128
max-player-distance-from-end-centre: 128

# |------------------------|
# |        Features        |
# |------------------------|

xp-drop:
  enabled: true

  # The way xp-per-player should be interpreted.
  # levels: The value is given in levels (e.g. 68 will add 68 to the XP number displayed to the player)
  #         This is useful to add a consistent number of points
  # points: The value is given in points, which changes based on the player's current XP
  #         i.e. 12000 points will not always equal 68 levels
  # DEFAULT: levels
  mode: levels

  # The amount of XP to give each Dragon fight participant upon Dragon death
  # This is interpreted differently depending on xp-mode
  # DEFAULT: 68
  xp-per-player: 68

decoration-orbs:
  enabled: true

  # The number of XP orbs spawned per player upon Dragon death (these are decorative only and have no XP value)
  # If there are a large number of players in the End upon Dragon death, having this too high may cause a lag spike
  # This will not be triggered if enable-xp-drop is disabled
  # DEFAULT: 8
  orb-count-per-player: 8

egg-respawn:
  enabled: true

  # The chance of the Dragon egg respawning upon Dragon defeat and when enable-egg-respawn is true
  # RANGE: 0.0-1.0 (0.0 = 0%, 1.0 = 100%)
  # DEFAULT: 1.0
  chance: 1.0

  # The message broadcasted when the Dragon egg respawns (leave blank to have no message)
  # MACROS:
  #   <position>: x, y, and z coordinates of the Egg (e.g. "x=0 y=68 z=0")
  # DEFAULT: ""
  announcement: ""

  # The coordinates of the Dragon egg when it spawns
  # DEFAULT: 0, 0, 0 (this does not need to be configured by default since the portal coordinates are always (0, 0))
  position:
    x: 0
    y: 0
    z: 0
    # Should the y coordinate specified here dictate exactly where the Dragon egg should go?
    # If false, the plugin will try to find an air block above a bedrock block
    # DEFAULT: false
    override-y: false

defeat-announcement:
  enabled: true

  # The message broadcasted when the Dragon is defeated
  # MACROS:
  #   <killer>: name of the player who killed the Dragon
  #   <participants>: list of players within max-player-distance-from-end-centre upon Dragon defeat (EXCEPT the killer)
  # DEFAULT: "&6<killer>&r just defeated the &5Ender Dragon&r!"
  one-participant: "&6<killer>&r just defeated the &5Ender Dragon&r!"

  # DEFAULT: "&6<killer>&r just defeated the &5Ender Dragon&r with help from <players-in-end>!"
  multiple-participants: "&6<killer>&r just defeated the &5Ender Dragon&r with help from <participants>!"

custom-commands:
  enabled: true

  # The commands to be run by the server when the Dragon is defeated
  # Note that they will always send command feedback to the server console and all online ops
  # MACROS:
  #   <killer>: name of the player who killed the Dragon
  #   <killer-display-name>: display name of the player who killed the Dragon (may be the same as <killer>, or e.g. the nickname of the player)
  #   <participants-list>: list of players within max-player-distance-from-end-centre upon Dragon defeat (e.g. "p1, p2, & p3") (EXCEPT the killer)
  #   <each-participant>: the command will be run individually for players within max-player-distance-from-end-centre upon Dragon defeat (EXCEPT the killer)
  # DEFAULT: []
  commands:
    #- "give <killer> minecraft:diamond 4"
    #- "give <each-participant> minecraft:iron_ingot 8"
    #- "say Congratulations <killer-display-name> and <participants-list>!"

  # The text to replace <participants-list> with if there are no Dragon fight participants other than the killer
  # E.g. (using the 3rd example command) "Congratulations dragonkiller495 and no-one else!"
  # DEFAULT: "no-one else"
  no-participants-filler: "no-one else"

# Customisation of the Dragon's bossbar
bossbar-customisation:
  enabled: false

  # List of possible names to be displayed above the bossbar (leave empty for "Ender Dragon")
  # DEFAULT: []
  names:
    #- "Bertha"

  # The colour of the bossbar
  # COLOURS: blue, green, pink, purple, red, white, yellow
  # DEFAULT: pink
  colour: pink

  # The style of the bossbar
  # STYLES: progress, notched_6, notched_10, notched_12, notched_20
  # DEFAULT: progress
  style: progress

dragon-respawn-cooldown:
  enabled: false

  # The delay in ticks before the Dragon can be respawned after having been defeated
  # The cooldown is reset when the server is restarted
  # DEFAULT: 6000 (5 minutes)
  cooldown: 6000

  # The message broadcasted when the Dragon respawn cooldown begins (if there is one)
  # MACROS:
  #   <time-remaining>: number of seconds before the cooldown ends
  # DEFAULT: "The <time-remaining>-second Dragon respawn cooldown has started!"
  enter-announcement: "The <time-remaining>-second Dragon respawn cooldown has started!"

  # The message broadcasted when the Dragon respawn cooldown ends
  # MACROS:
  #   <cooldown-length>: number of seconds the cooldown lasts; dragon-respawn-cooldown / 20
  # DEFAULT: "The <cooldown-length>-second Dragon respawn cooldown has ended!"
  leave-announcement: "The <cooldown-length>-second Dragon respawn cooldown has ended!"

  # The message sent to a player who tries to place an End Crystal to respawn the Dragon when the cooldown is active
  # MACROS:
  #   <time-remaining>: number of seconds before the cooldown ends
  # DEFAULT: "The Ender Dragon cannot be respawned at the moment because it's in cooldown. Cooldown time left: &r<time-remaining> seconds"
  warning: "&cThe Ender Dragon cannot be respawned at the moment because it's in cooldown. Cooldown time left: &r<time-remaining> seconds"

statistics:
  enabled: false
