# EnderDragonTweaks - Ender Dragon tweaks, mainly for SMP servers
# by EvsDev (https://github.com/evs-dev)
# CONFIGURATION FILE

# Is the plugin enabled? Should the Dragon death event be registered?
# DEFAULT: true
enabled: true

# The delay in ticks (20 ticks = 1 second) between the death of the Dragon and when this plugin triggers
# DEFAULT: 80
delay: 80

# |------------------------|
# |        Features        |
# |------------------------|

# Should every player in the End receive XP upon Dragon death?
enable-xp-drop: true

# Should every player in the End have decorative (valueless) XP orbs spawned above them upon Dragon death?
enable-decoration-orbs: true

# Should the Dragon egg respawn every time the Dragon is defeated?
enable-egg-respawn: true

# Should a message be broadcasted when the Dragon is defeated?
enable-defeat-announcement: true

# |------------------------|
# |        Settings        |
# |------------------------|

# The radius (in blocks) from the centre of the End island where players will be counted as Dragon fight participants
# DEFAULT: 128
max-player-distance-from-end-centre: 128

# The number of experience points to give each player in the End upon Dragon death
# DEFAULT: 12000 (68 levels)
xp-points-per-player: 12000

# The number of XP orbs spawned per player upon Dragon death (these are decorative only and have no XP value)
# If there are a large number of players in the End upon Dragon death, having this too high may cause a lag spike
# This will not be triggered if enable-xp-drop is disabled
# DEFAULT: 8
orb-count-per-player: 8

# The coordinates of the Dragon egg when it spawns
# DEFAULT: 0, 0, 0 (this does not need to be configured by default since the portal coordinates are always (0, 0))
egg-position:
  x: 0
  y: 0
  z: 0
  # Should the y coordinate specified here dictate exactly where the Dragon egg should go?
  # If false, the plugin will try to find an air block above a bedrock block
  # DEFAULT: false
  override-y: false
  
# The message broadcasted when the Dragon is defeated
# Colour/formatting codes are supported using the ampersand (&) symbol (https://minecraft.gamepedia.com/Formatting_codes#Color_codes)
# !!! QUOTES ("") ARE REQUIRED !!!
# Macros are replaced when the message is sent
# MACROS:
#   <killer>: name of the player who killed the Dragon
#   <players-in-end>: list of players within max-player-distance-from-end-centre upon Dragon defeat
# DEFAULT: "&6<killer>&r just defeated the &5Ender Dragon&r with help from <players-in-end>!"
defeat-announcement-message: "&6<killer>&r just defeated the &5Ender Dragon&r with help from <players-in-end>!"
