main: me.EvsDev.EnderDragonTweaks.Main
name: EnderDragonTweaks
version: 1.5.0
description: "Ender Dragon tweaks (for survival) by Evs"
author: EvsDev
api-version: 1.16
commands:
  respawndragon:
    description: "Respawns the Ender Dragon as if a player placed End Crystals on the End Portal"
    usage: /<command> [overrideCooldown|heedCooldown]
permissions:
  enderdragontweaks.respawndragon:
    description: Allows usage of /respawndragon command
    default: op